### ISSUE TITLE
Setting disabled through setState 

### ISSUE THREAD

**Issue by CamiloTerevinto** [jacklam718/react-native-button-component#26]
I am using this:

import { RoundButton } from 'react-native-button-component';

```
<View style={{width: "100%", justifyContent: "center", alignItems: "center"}}>
    <RoundButton text="Terminar compra" onPress={() => navigate("PurchaseConfirmation", { data: this.state.basket})} 
        disabled={this.state.anyProductSelected == false}
        style={{width: 125, height: 35, marginBottom: 5, marginTop: 5}}>
    </RoundButton>
</View>
```
And I am updating the state with:

```
addHandler = (index: number, product: Product) : number => {
        ...
        this.setState({ anyProductSelected: true});
    }
```

But the button stays disabled (while the rest of the UI updates just fine).

Am I doing something wrong or this not supported?

More data:
- "react": "16.0.0-alpha.12",
- "react-native": "^0.47.1",
- "react-native-button-component": "^0.1.24",
- typescript 2.3
- Android 7 (emulator)

**Comment by CamiloTerevinto** [comment]
If I instead use the multiple state support like this:

```
<RoundButton buttonState={this.state.buttonState}
    states={{
       disabled: {
           text: "Terminar compra",
           disabled: true,
           backgroundColors: ["#fff", "#fff"],
           style: {width: 125, height: 35, marginBottom: 5, marginTop: 5}
        },
        enabled: {
            text: "Terminar compra",
            disabled: false,
            backgroundColors: ["#4dc7a4", "#4dc7a4"],
            style: {width: 125, height: 35, marginBottom: 5, marginTop: 5},
            onPress: () => navigate.navigate("PurchaseConfirmation", { data: this.state.basket})
        }
    }}>
</RoundButton>
```

Then:
- I can click the button
- The button changes to the appropriate color BUT is dimmed as if it was disabled
- Upon click the button the color turns to the actual enabled color
- The transition effect is not nice for a disabled->enabled transition

**Comment by jacklam718** [comment]
@CamiloTerevinto Thanks for report the issue with detailed information. I just fixed the issue it building on Travis CI now, will let you know when it's done.

**Comment by jacklam718** [comment]
@CamiloTerevinto Fixed in `v0.1.25`

**Comment by CamiloTerevinto** [comment]
@jacklam718  Glad to hear that, which of the two problems did you fix?

**Comment by jacklam718** [comment]
@CamiloTerevinto First one

**Comment by jacklam718** [comment]
@CamiloTerevinto I only fixed can not update `disabled` state issue.

**Comment by CamiloTerevinto** [comment]
@jacklam718  Do I need to re-run `react-native link`? I still have the problem after `npm-update` installed `0.1.25`

**Comment by jacklam718** [comment]
@CamiloTerevinto Same issue?

**Comment by CamiloTerevinto** [comment]
@jacklam718  Yes, the problem (first case) still exists. I just reinstalled the application on the emulator to confirm.

**Comment by jacklam718** [comment]
@CamiloTerevinto 
I would suggest:
* Kill your react-native's dev server
* Remove **npm_modules**
* Run `yarn` OR `npm install` to install dependencies  (make sure the version of react-native-button-component is correct)
* Start you react-native dev server again by `npm start`

**Comment by CamiloTerevinto** [comment]
@jacklam718  I have just done this:

1. remove the app from the emulator
2. close the react-native server
3. delete node_modules
4. run npm install 
5. checked that your package.json says "0.1.25"
6. run react-native run-android

Problem still exists unfortunately. I added this to confirm it's not something I'm doing wrong:

<Text>{this.state.anyProductSelected.toString()}</Text>

This shows: "false" then "true" as expected, but the button is still disabled

**Comment by jacklam718** [comment]
@CamiloTerevinto 
Run this command `cat node_modules/react-native-button-component/package.json | grep "version"` to check the version.

**Comment by jacklam718** [comment]
@CamiloTerevinto Is it really `0.1.25`?

**Comment by CamiloTerevinto** [comment]
@jacklam718 As you can see in the following image, it is really 0.1.25:

![version](https://user-images.githubusercontent.com/6320854/29744781-4dc9a00c-8a82-11e7-8f86-505b3089698c.PNG)

**Comment by jacklam718** [comment]
@CamiloTerevinto Then nothing can help you. You can just fork this repo and directly change it.

**Comment by CamiloTerevinto** [comment]
@jacklam718  I've spent some time debugging the dist code, this is what's causing the problem:

```
componentWillReceiveProps(nextProps) {
    if (this.props.buttonState !== nextProps.buttonState) {
      this.setState({
        currentButton: this.getCurrentButton(nextProps),
      });
    }
  }
```

I believe this is wrong and should instead be: 

```
componentWillReceiveProps(nextProps) {
    if (this.props !== nextProps) {
      this.setState({
        currentButton: this.getCurrentButton(nextProps),
      });
    }
  }
```

Since otherwise only a change of state will actually make the button re-render.

**Comment by jacklam718** [comment]
@CamiloTerevinto 

this one works for me 
```javascript
componentWillReceiveProps(nextProps) {
    if (this.props.buttonState !== nextProps.buttonState) {
      this.setState({
        currentButton: this.getCurrentButton(nextProps),
      });
    }
  }
```

here is my code: 
```javascript
<View style={styles.container}>
  <GroupContainer
    groupTitle="Button"
  >
    <ButtonComponent
      backgroundColors={['#212122', '#414141']}
      text={'Button'.toUpperCase()}
      onPress={() => {
        this.setState({ disabled: !this.state.disabled });
      }}
    />
  </GroupContainer>

  <GroupContainer
    groupTitle="Icon Button"
  >
    <ButtonComponent
      disabled={this.state.disabled}
      image={require('../img/settings.png')}
      text={'Icon Buttons'.toUpperCase()}
      onPress={() => {

      }}
    />
  </GroupContainer>
</View>
```

**Comment by jacklam718** [comment]
@CamiloTerevinto 
Seems this is wrong logic
```javascript
<View style={{width: "100%", justifyContent: "center", alignItems: "center"}}>
    <RoundButton text="Terminar compra" onPress={() => navigate("PurchaseConfirmation", { data: this.state.basket})} 
        disabled={this.state.anyProductSelected == false}
        style={{width: 125, height: 35, marginBottom: 5, marginTop: 5}}>
    </RoundButton>
</View>
```
And I am updating the state with:

```javascript
addHandler = (index: number, product: Product) : number => {
        ...
        this.setState({ anyProductSelected: true});
    }
```

When you update `anyProductSelected` to `true`
* `anyProductSelected is true`
* `anyProductSelected == false #result will be equal false`

**Comment by CamiloTerevinto** [comment]
@jacklam718 my logic is correct. The component starts with anyProductSelected == false so the button has disabled = true. Then the user selects a product so anyProductSelected == true and the button should enable.

**Comment by CamiloTerevinto** [comment]
@jacklam718  your code is wrong because, due to this:

```
  componentWillReceiveProps(nextProps) {
    if (this.props.buttonState !== nextProps.buttonState) {
      this.setState({
        currentButton: this.getCurrentButton(nextProps),
      });
    }
  }
```

When it gets to this part:

```
  render() {
    ....
    const disabled = this.getProp('disabled');
```

disabled == true **because you are not updating the props**. If you debugged your own code as I did, you'd realize of this

**Comment by jacklam718** [comment]
@CamiloTerevinto Did you see my screenshot?

**Comment by CamiloTerevinto** [comment]
@jacklam718  As I said, I'm expecting the button to be **enabled** when **anyProductSelected == true**. Your screenshot suggest I'm expecting the reverse which is incorrect

**Comment by jacklam718** [comment]
@CamiloTerevinto 
Basic programming question  `true == false` 
what's the result? can you tell me?

**Comment by jacklam718** [comment]
@CamiloTerevinto Can you answer me that programming question?

**Comment by CamiloTerevinto** [comment]
@jacklam718  once again because you don't understand:

```
<RoundButton disabled={this.state.anyProductSelected == false}></Button
```

Cases:
- **anyProductSelected = false** => `disabled={true}` => button is **disabled**
-**anyProductSelected = true** => `disabled={false}` => button is **enabled**

**Comment by jacklam718** [comment]
@CamiloTerevinto Just answer my question 
1. this.state.anyProductSelected = true
2. this.state.anyProductSelected == false #whats the result?

**Comment by CamiloTerevinto** [comment]
@jacklam718  wow you are a real idiot. You don't understand English so you blame it on me. I have over 4 years of programming experience you don't need to tell me how it works you little kid. Learn English and accept the fact you are dead wrong in this post. I'm done with your stupidity

**Comment by jacklam718** [comment]
@CamiloTerevinto 
OK forget it. Let me tell you the answer.

![screen shot 2017-08-27 at 9 16 33 pm](https://user-images.githubusercontent.com/5494638/29750147-31d0472a-8b6d-11e7-90e5-74794095ace8.png)

**Comment by jacklam718** [comment]
@CamiloTerevinto Please take a look. you're passing `false` into the component

**Comment by CamiloTerevinto** [comment]
@jacklam718  That's **WHAT I AM EXPECTING.** Can't you understand English? **THAT'S EXPECTED, THAT'S WHAT I WANT** Wow you are a real noob. I **WANT** to pass **false** because that's how **MY LOGIC** works.

**Comment by jacklam718** [comment]
@CamiloTerevinto OK fine. **Don't use this component** if you don't like
